name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            sudo apt-get update
            # Check if port 1337 is in use and kill the process if it is running
            if lsof -i:1337 > /dev/null 2>&1; then
                PID=$(lsof -t -i:1337)
                echo "Killing process on port 1337 with PID $PID"
                kill -9 $PID
            else
                echo "No service running on port 1337."
            fi

            # Define project directory
            PROJECT_DIR="/home/ubuntu/simple-strapi"

            # Remove the existing directory if it exists to avoid conflicts
            if [ -d "$PROJECT_DIR" ]; then
               sudo rm -rf "$PROJECT_DIR"
            fi
            
            sudo apt install npm -y
            git clone https://github.com/Pramod858/simple-strapi.git
            cd simple-strapi
            chmod +x generate_env_var.sh
            ./generate_env_var.sh
            npm install
            nohup npm run develop > strapi.log 2>&1 &
            sleep 240
            
            # Check if the service is running on port 1337
            if lsof -i:1337 > /dev/null 2>&1; then
                echo "Service is running on port 1337."
            else
                echo "No service running on port 1337."
                exit 1
            fi
          EOF
