name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
          sudo apt update
          sudo apt install -y nodejs npm
          sudo npm install -g pm2
          git clone https://github.com/username/simple-strapi.git
          cd simple-strapi
          chmod +x generate_env_var.sh
          ./generate_env_var.sh
          npm install
          npm run build
          echo "Waiting for the service to be up and running..."
          sleep 300
          echo "Script ran successfully."
          echo "Running on http://localhost:1337/admin"
