name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            sudo apt-get update
            sudo apt install npm -y
            git clone https://github.com/Pramod858/simple-strapi.git
            cd simple-strapi
            chmod +x generate_env_var.sh
            ./generate_env_var.sh
            npm install
            nohup npm run develop > strapi.log 2>&1 &
            sleep 240
            # Check if port 1337 is in use
            if lsof -i:1337 > /dev/null 2>&1; then
                echo "Service is running on port 1337."
            else
                echo "No service running on port 1337."
                exit 1
            fi
          EOF
