name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          ssudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
          sudo bash nodesource_setup.sh
          sudo apt-get install -y nodejs
          sudo npm install -g yarn pm2
          cd /home/$EC2_USER
          mkdir -p /home/$EC2_USER/simple-strapi
          cd /home/$EC2_USER/simple-strapi
          nohup bash -c "echo -e 'skip\n' | npx create-strapi-app@latest . --quickstart &"
          cd /home/$EC2_USER/simple-strapi
          pm2 start npm --name "strapi-app" -- run develop
          echo "Waiting for the service is up and running..."
          sleep 300
          echo "Script ran successfully."
          echo "running on http://localhost:1337/admin"
        EOF
