name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
          sudo bash nodesource_setup.sh
          sudo apt-get install -y nodejs
          sudo npm install -g yarn pm2

          cd /home/$EC2_USER

          # Check if the Strapi service is running
          if pm2 list | grep -q strapi-app; then
            echo "Strapi service is running. Stopping and deleting it..."
            pm2 stop strapi-app
            pm2 delete strapi-app
            rm -rf /home/$EC2_USER/simple-strapi
          else
            echo "Strapi service is not running."
          fi

          # Create a new Strapi app
          echo "Creating a new Strapi app..."
          nohup bash -c "echo -e 'skip\n' | npx create-strapi-app@latest simple-strapi --quickstart &"
          sleep 300

          cd simple-strapi
          pm2 start npm --name "strapi-app" -- run develop
          echo "Waiting for the service to be up and running..."
          sleep 300
          echo "Script ran successfully."
          echo "Running on http://localhost:1337/admin"
        EOF
